package services

import (
	"path/filepath"
	"regexp"
	"strings"
)

// maxIndexFileBytes skips bundles and minified output that would flood the graph.
const maxIndexFileBytes = 2 << 20

var (
	generatedMarkerRe = regexp.MustCompile(`(?i)(code generated\b.*\bdo not edit|@generated\b|auto-?generated|automatically generated|generated by (?:the )?(?:protoc|protobuf|thrift|swagger|openapi|bindgen|cython|antlr|yacc|bison|flex|grpc|mockgen|stringer|sqlc)|do not edit (?:this file )?(?:manually|by hand))`)
	generatedNameRe   = regexp.MustCompile(`(?i)(\.pb\.go|\.pb\.cc|\.pb\.h|_pb2(?:_grpc)?\.pyi?|\.min\.js|\.bundle\.js|_generated\.\w+|\.generated\.\w+|\.gen\.go|_gen\.go|_mock\.go)$`)
)

// isGenerated reports whether a source file looks machine-generated, judging by
// its name and by markers in its first lines. Generated code is still indexed
// (callers and inheritance stay accurate) but flagged so searches can hide it.
func isGenerated(path, content string) bool {
	if isGeneratedName(path) {
		return true
	}
	head := content
	lines := strings.SplitN(content, "\n", 21)
	if len(lines) > 20 {
		head = strings.Join(lines[:20], "\n")
	}
	if len(head) > 2048 {
		head = head[:2048]
	}
	return generatedMarkerRe.MatchString(head)
}

func isGeneratedName(path string) bool {
	return generatedNameRe.MatchString(filepath.Base(path))
}
