package services

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"codergag/internal/graph"
)

func TestIsGenerated(t *testing.T) {
	cases := []struct {
		path, content string
		want          bool
	}{
		{"x.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n", true},
		{"x.py", "# @generated by tool\n", true},
		{"x.ts", "/* auto-generated file */\n", true},
		{"api.pb.go", "package x\n", true},
		{"a_pb2.py", "import x\n", true},
		{"app.min.js", "var a;", true},
		{"x.go", "package x\n// hand written, mentions generated code in passing\nfunc F() {}\n", false},
		{"x.go", strings.Repeat("// filler\n", 30) + "// Code generated by x. DO NOT EDIT.\n", false}, // marker beyond header
		{"main.go", "package main\n", false},
	}
	for _, c := range cases {
		if got := isGenerated(c.path, c.content); got != c.want {
			t.Errorf("isGenerated(%q, %.30q) = %v, want %v", c.path, c.content, got, c.want)
		}
	}
}

func writeFiles(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestGeneratedCodeIsFlaggedHiddenFromSearchButStillLinked(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"real.go": "package x\nfunc UseIt() { ParseThing() }\n",
		"gen.go":  "// Code generated by mockgen. DO NOT EDIT.\npackage x\nfunc ParseThing() {}\n",
	})
	app := ApplicationInMemory()
	if _, err := app.Index.IndexRepository("p", dir, true, nil, false); err != nil {
		t.Fatal(err)
	}
	hidden, _ := app.Code.Search("p", "parse thing", 10, false)
	if len(hidden) != 0 {
		t.Fatalf("generated function should be hidden by default: %v", hidden)
	}
	shown, _ := app.Code.Search("p", "parse thing", 10, true)
	if len(shown) != 1 || shown[0]["generated"] != true {
		t.Fatalf("include_generated should return the flagged function: %v", shown)
	}
	// Calls into generated code are still recorded.
	if got := callTargets(t, app, "p", "UseIt"); len(got) != 1 {
		t.Fatalf("call into generated code lost: %v", got)
	}
}

func TestCommitCacheIsBounded(t *testing.T) {
	commitMu.Lock()
	original := commitCache
	commitCache = map[string]struct {
		sha string
		at  time.Time
	}{}
	commitMu.Unlock()
	t.Cleanup(func() {
		commitMu.Lock()
		commitCache = original
		commitMu.Unlock()
	})
	now := time.Now()
	for i := 0; i < maxCommitCacheEntries+16; i++ {
		commitMu.Lock()
		commitCache[fmt.Sprintf("/repo-%d", i)] = struct {
			sha string
			at  time.Time
		}{at: now.Add(-time.Duration(i) * time.Second)}
		commitMu.Unlock()
	}
	commitMu.Lock()
	pruneCommitCache(now)
	got := len(commitCache)
	commitMu.Unlock()
	if got > maxCommitCacheEntries {
		t.Fatalf("commitCache = %d, want at most %d", got, maxCommitCacheEntries)
	}
}

func TestOversizedFilesAreSkipped(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{"big.js": "function a(){}\n" + strings.Repeat("//x\n", maxIndexFileBytes/4)})
	app := ApplicationInMemory()
	if _, err := app.Index.IndexRepository("p", dir, true, nil, false); err != nil {
		t.Fatal(err)
	}
	if fns, _ := app.Graph.FindNodes("Function", map[string]any{"project_id": "p"}); len(fns) != 0 {
		t.Fatalf("oversized file should not be indexed, found %d functions", len(fns))
	}
}

func TestIncrementalIndexReusesGraphifyRun(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"go.mod": "module x\n",
		"a.go":   "package x\nfunc A() {}\n",
	})
	app := ApplicationInMemory()
	if _, err := app.Index.IndexRepository("p", dir, true, nil, false); err != nil {
		t.Fatal(err)
	}
	writeFiles(t, dir, map[string]string{"a.go": "package x\nfunc A() {}\nfunc B() {}\n"})
	if _, err := app.Index.IndexRepository("p", dir, true, nil, false); err != nil {
		t.Fatal(err)
	}
	runs, err := app.Graph.FindNodes("GraphifyRun", map[string]any{"project_id": "p"})
	if err != nil {
		t.Fatal(err)
	}
	if len(runs) != 1 {
		t.Fatalf("GraphifyRun nodes = %d, want 1", len(runs))
	}
}

func TestStaleCallEdgesAreRemoved(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{"a.go": "package x\nfunc A() { B(); C() }\nfunc B() {}\nfunc C() {}\n"})
	app := ApplicationInMemory()
	app.Index.IndexRepository("p", dir, true, nil, false)
	if got := callTargets(t, app, "p", "A"); len(got) != 2 {
		t.Fatalf("setup: %v", got)
	}
	// A no longer calls C.
	writeFiles(t, dir, map[string]string{"a.go": "package x\nfunc A() { B() }\nfunc B() {}\nfunc C() {}\n"})
	app.Index.IndexRepository("p", dir, true, nil, false)
	got := callTargets(t, app, "p", "A")
	if len(got) != 1 || !strings.HasSuffix(got[0], ":B") {
		t.Fatalf("stale A->C edge should be gone: %v", got)
	}
}

func TestStaleCrossFileImplementsEdgeIsRemoved(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"types.rs": "struct Circle {}\ntrait Shape {}\n",
		"impl.rs":  "impl Shape for Circle {}\n",
	})
	app := ApplicationInMemory()
	app.Index.IndexRepository("p", dir, true, nil, false)
	if got := edgeTargets(app, "p", "IMPLEMENTS", "Circle"); len(got) != 1 {
		t.Fatalf("setup: %v", got)
	}
	writeFiles(t, dir, map[string]string{"impl.rs": "// impl removed\n"})
	app.Index.IndexRepository("p", dir, true, nil, false)
	if got := edgeTargets(app, "p", "IMPLEMENTS", "Circle"); len(got) != 0 {
		t.Fatalf("stale IMPLEMENTS edge survived removal of the impl: %v", got)
	}
}

func TestRemoveEdgesPersists(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "g.gob")
	repo, err := graph.NewPersistentRepository(dbPath)
	if err != nil {
		t.Fatal(err)
	}
	a, _ := repo.UpsertNode("Function", map[string]any{"project_id": "p", "qualified_name": "a"}, nil)
	b, _ := repo.UpsertNode("Function", map[string]any{"project_id": "p", "qualified_name": "b"}, nil)
	e1, _ := repo.Link("CALLS", a.ID, b.ID, map[string]any{"source": "x"})
	repo.Link("REFERENCES", a.ID, b.ID, nil)
	if err := repo.RemoveEdges([]string{e1.ID}); err != nil {
		t.Fatal(err)
	}
	repo.Close()
	repo, _ = graph.NewPersistentRepository(dbPath)
	defer repo.Close()
	if n, _ := repo.Neighbors(a.ID, "CALLS", graph.DirOut); len(n) != 0 {
		t.Fatalf("removed edge came back after reload: %d", len(n))
	}
	if n, _ := repo.Neighbors(a.ID, "REFERENCES", graph.DirOut); len(n) != 1 {
		t.Fatalf("unrelated edge lost: %d", len(n))
	}
}

func TestSourceFileNodesCarryTheGeneratedFlag(t *testing.T) {
	app, _ := indexTree(t, map[string]string{"gen.go": "// Code generated by x. DO NOT EDIT.\npackage x\nfunc G() {}\n", "real.go": "package x\nfunc R() {}\n"})
	files, _ := app.Graph.FindNodes("SourceFile", map[string]any{"project_id": "p"})
	got := map[string]bool{}
	for _, f := range files {
		g, _ := f.Properties["generated"].(bool)
		got[strProp(f, "rel_path")] = g
	}
	if !got["gen.go"] || got["real.go"] {
		t.Fatalf("SourceFile generated flags: %v", got)
	}
}
